<script setup>
import { ref } from 'vue'
import { chatAboutText } from '../services/api'
const props = defineProps({ selectedText: String, article: Object })
const question = ref('为什么这里要这样表达？'), answer = ref(''), related = ref([]), loading = ref(false), error = ref('')
async function submit() { if (!props.selectedText || !question.value.trim()) return; loading.value = true; error.value = ''; try { const data = await chatAboutText(question.value.trim(), props.selectedText, '', props.article); answer.value = data.answer; related.value = data.related_questions || [] } catch { error.value = '追问服务暂时不可用，请稍后重试。' } finally { loading.value = false } }
</script>
<template><section class="chat-panel"><h3>围绕原文提问</h3><label>选中内容</label><blockquote>{{ selectedText || '请先选中正文' }}</blockquote><textarea v-model="question" :disabled="!selectedText" placeholder="例如：为什么这里是宾语前置？" @keydown.meta.enter="submit" /><button class="ask-button" :disabled="!selectedText || loading" @click="submit">{{ loading ? '正在思考…' : '提交问题' }}</button><p v-if="error" class="chat-error">{{ error }}</p><div v-if="answer" class="chat-answer"><label>回答</label><p>{{ answer }}</p><button v-for="item in related" @click="question=item">{{ item }}　›</button></div></section></template>
<style scoped>.chat-panel{padding:12px 2px;color:#ccc}.chat-panel h3{font-size:18px;color:#eee;margin:5px 0 18px}.chat-panel label{display:block;font-size:12px;color:#888;margin-bottom:7px}.chat-panel blockquote{margin:0 0 14px;padding:11px;border-left:2px solid #ddd;background:#1b1b1b;color:#eee;line-height:1.6}.chat-panel textarea{width:100%;min-height:92px;resize:vertical;border:1px solid #484848;border-radius:6px;background:#131313;color:#eee;padding:10px;outline:none;line-height:1.55}.ask-button{margin-top:10px;border:1px solid #aaa;border-radius:6px;background:#eee;color:#111;padding:8px 13px;cursor:pointer}.ask-button:disabled{opacity:.5;cursor:default}.chat-error{color:#bbb;font-size:13px}.chat-answer{margin-top:20px;padding-top:15px;border-top:1px solid #383838}.chat-answer p{line-height:1.7;color:#ccc;font-size:14px}.chat-answer button{display:block;width:100%;text-align:left;border:0;background:none;color:#ddd;padding:8px 0;cursor:pointer}</style>
