<script setup>
import { computed, ref, watch } from 'vue'; import TextSelectionToolbar from './TextSelectionToolbar.vue'
const props = defineProps({ article: Object, previousArticle: Object, nextArticle: Object, articlePosition: Number, articleTotal: Number }); const emit = defineEmits(['select-text', 'select-tool', 'navigate']); const toolbar = ref(false), position = ref({}), activeTab = ref('original'), readerEl = ref(null)
const tabContent = computed(() => ({ original: props.article.content, notes: ['谪守：因罪贬谪，出任外地官职。', '越明年：到了第二年。越，到。', '迁客骚人：被贬谪的官员和失意的文人。', '不以物喜，不以己悲：不因外物好坏和自身得失而或喜或悲。'], translation: ['庆历四年春天，滕子京被贬任巴陵郡太守。到了第二年，政事顺利，百姓和乐，各种荒废的事业都兴办起来。', '我看那巴陵郡的美景，全在洞庭湖上。它连接着远方的山，吞吐着长江的水，浩浩荡荡，无边无际。'], appreciation: ['《岳阳楼记》以洞庭湖的阴晴变化映照人的悲喜，进而超越个人得失，提出“先忧后乐”的公共理想。', '文章由楼写景，由景入情，再由情入理，层层推进，节奏开阔。'] }[activeTab.value] || props.article.content))
function onSelect() { const selection = window.getSelection(), text = selection?.toString().trim(); if (!text) return; const range = selection.getRangeAt(0), rect = range.getBoundingClientRect(); emit('select-text', text); position.value = { left: `${Math.max(300, rect.left + rect.width / 2 - 190)}px`, top: `${Math.max(125, rect.top - 66)}px` }; toolbar.value = true }
function choose(mode) { emit('select-tool', mode); toolbar.value = false; window.getSelection()?.removeAllRanges() }
watch(() => props.article.id, () => { activeTab.value = 'original'; toolbar.value = false; readerEl.value?.scrollTo({ top: 0, behavior: 'smooth' }) })
</script>
<template><section ref="readerEl" class="reader" @mouseup="onSelect"><div class="reader-inner"><div class="breadcrumb">首页　/　{{ article.dynasty }}　/　{{ article.author }}　/　{{ article.title }}</div><h1>{{ article.title }}</h1><div class="author">{{ article.author }}　 {{ article.dynasty }}</div><div class="reader-tabs"><button v-for="[key,label] in [['original','原文'],['notes','注释'],['translation','译文'],['appreciation','赏析']]" :class="{active:activeTab===key}" @click="activeTab=key">{{ label }}</button></div><div class="hint">{{ activeTab === 'original' ? '试试选中正文中的一句话。' : '不同阅读层可帮助你理解字词、语义和写作结构。' }}</div><article :class="`article-${activeTab}`"><p v-for="(paragraph, index) in tabContent" :key="index">{{ paragraph }}</p></article><footer class="article-pager"><button :disabled="!previousArticle" @click="$emit('navigate', 'previous')">‹　{{ previousArticle ? '上一篇' : '已经是第一篇' }}</button><span>第 {{ articlePosition }} / {{ articleTotal }} 篇</span><button :disabled="!nextArticle" @click="$emit('navigate', 'next')">{{ nextArticle ? '下一篇' : '已经是最后一篇' }}　›</button></footer></div><TextSelectionToolbar :visible="toolbar" :position="position" @tool="choose" /></section></template>
<style scoped>.article-pager{display:flex;align-items:center;justify-content:space-between;margin-top:34px;padding-top:22px;border-top:1px solid #3d3d3d}.article-pager button{border:1px solid #888;border-radius:7px;background:#181818;color:#eee;padding:9px 14px;cursor:pointer}.article-pager button:disabled{border-color:#343434;color:#666;cursor:default}.article-pager span{font-size:13px;color:#999}</style>
